---
training_filename: ../rust-boost/tests/data/a1a.t
training_is_binary: false
training_bytes_per_example: 0
testing_filename: ../rust-boost/tests/data/a1a.t
testing_is_binary: false
testing_bytes_per_example: 0
num_examples: 30956
num_testing_examples: 30956
num_features: 125
range:
  start: 0
  end: 125
max_sample_size: 20000
max_bin_size: 10
default_gamma: 0.25
min_ess: 0.5
num_iterations: 64
max_leaves: 2
max_trials_before_shrink: 20000
channel_size: 128
buffer_size: 20000
batch_size: 1000
parallel_sampling: true
sampler_num_threads: 2
sampler_init_grid_size: 1.0
sampler_average_window_size: 1000
num_examples_per_block: 128
disk_buffer_filename: stratified.bin
num_assigners: 2
num_selectors: 2
network: []
port: 8888
local_name: local_worker